### PR TITLE
Added base preprocessing files in order to generate labeled dataset f…

### PR DESCRIPTION
**Pull request by martingajek**
…rom semcor xml files and the nltk wordnet corpus.

### CODE REVIEW

**Review by ninalopatina — APPROVED** [review]
Code looks pretty good overall, great progress! A few notes:

- its disambiguation, not disembiguation
- I would give the repo a shorter name, RuGlossBERT, or EnRuWSD - at the least, shorten word sense disambiguation to WSD, since anyone who knows what the former is knows the acronym. 
- at this stage in the project, the README should include instructions for how to set up the repo and run it. What data should the user download, and where does it go? Where's the command line interface line to run to run everything? What happens when you run it? These should all be answered in the next pull request, and some of the instructions for starting a repo (that you have already completed) should be removed.

**Comment by martingajek** [comment]
Hi Nina
Thank you very much for reviewing the code. For the moment I am testing the full pipeline (on the English dataset) in an Ipython notebook. After a bunch of bug fixes It is running ok on GPU. I’ll commit a python script to run the training tonight. I will talk to you on hangouts at 6.
Best
Martin

**Comment by ninalopatina** [comment]
Ok, talk to you then. The notebook should be in the repo until you have a training script.


[cid:image002.png@01D551B4.1C88FB00]

Nina Lopatina
IQT Labs<http://www.iqt.org/labs>
Data Scientist
M: 650.441.0958

On Sep 25, 2019, at 4:45 PM, tintamarre1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Nina
Thank you very much for reviewing the code. For the moment I am testing the full pipeline (on the English dataset) in an Ipython notebook. After a bunch of bug fixes It is running ok on GPU. I’ll commit a python script to run the training tonight. I will talk to you on hangouts at 6.
Best
Martin

Sent from my iPhone

> On Sep 25, 2019, at 4:19 PM, Nina Lopatina <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Merged #1 into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftintamarre1%2FNLP_word_sense_disembiguation%2Fpull%2F1%3Femail_source%3Dnotifications%26email_token%3DAEENTJQZ3QJ5XT6QQSGRKPTQLPZYXA5CNFSM4IYRK4JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7TYTFY%23issuecomment-535267735&data=02%7C01%7Cnlopatina%40iqt.org%7Ce32769fbd2554b27176408d742126a8e%7C4e14f559d5ad4de78710d763a7bf84d8%7C0%7C0%7C637050519187235346&sdata=lfFLGvkweIl%2FA%2Fc3c037g%2BioeIRZwGhcrZCgJbVDw8Q%3D&reserved=0>, or mute the thread<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEENTJUATMVK6S3I5DTQFSDQLPZYXANCNFSM4IYRK4JA&data=02%7C01%7Cnlopatina%40iqt.org%7Ce32769fbd2554b27176408d742126a8e%7C4e14f559d5ad4de78710d763a7bf84d8%7C0%7C0%7C637050519187235346&sdata=CYntG6vTbH5%2BE04KhhF64c7WAmal48DAFWv2BruJkg4%3D&reserved=0>.




"This e-mail, and any attachments hereto, may contain information that is privileged, proprietary, confidential and/or exempt from disclosure under law and are intended only for the designated addressee(s). If you are not the intended recipient of this message, or a person authorized to receive it on behalf of the intended recipient, you are hereby notified that you must not use, disseminate, copy in any form, or take any action based upon the email or information contained therein.

If you have received this email in error, please permanently and immediately delete it and any copies of it, including any attachments, and promptly notify the sender at In-Q-Tel by reply e-mail, fax: 703-248-3001, or phone: 703-248-3000. Thank you for your cooperation.

For information about how we use personal data that you provide to us either directly or that we collect through your use of this Website, and applicable rights under the EU GDPR, please see our Privacy Policy, which can be found here http://www.iqt.org/privacy-policy. "

**Comment by martingajek** [comment]
Hi Nina
I just pushed some preprocessed sample data as well as a notebook for the training to the repo.
I added a requirements file (I suspect the latter needs to be cleaned a little bit since I’m using a lot of extra packages).
And thanks for catching the typo in the title, here’s the new url:

https://github.com/tintamarre1/NLP_word_sense_disambiguation.git
Best
Martin

**Pull request merged**
